### ISSUE TITLE
Rewrite Parser & Runtime Semantics

### ISSUE THREAD

**Issue by devsnek** [engine262/engine262#103]
Work ongoing.

**Comment by devsnek** [comment]
@ExE-Boss would you be interested in helping with this? It will help me be able to merge your other PRs faster.

**Comment by ExE-Boss** [comment]
This feels like it got completed in <https://github.com/engine262/engine262/commit/8ba3cee8380811d92a518bf24cce3c41ca7161d5>.

**Comment by devsnek** [comment]
Nah, it's almost complete though. there are still 500ish failing tests (not counting regex)
