### ISSUE TITLE
Readme example code is incomplete

### ISSUE THREAD

**Issue by bendtherules** [engine262/engine262#104]
The readme example code which imports the lib and runs a script is incomplete. 
It uses the print function, but that is not defined - and there is no indication that you need to actually implement it depending on your running environment.

I think it's reasonable too add a basic console.log implementation, as it will work in node and browser.
Like this -
```js
const print = new Value(realm, (args) => {
  console.log(args);
  return Value.undefined;
});
Abstract.CreateDataProperty(realm.global, new Value(realm, "print"), print);
```

**Comment by devsnek** [comment]
it should probably map through inspect as well. prs welcome.

**Comment by bendtherules** [comment]
Yes, that makes sense. Found the snippet from public demo.
Will raise a PR.
