### ISSUE TITLE
BigInt number in /dist/engine262.js breaks coverage instrumentation

### ISSUE THREAD

**Issue by rwaldron** [engine262/engine262#138]
After building the latest engine262, I tried to run `nyc --reporter=lcov npm run test`

```
failed to instrument /Users/rwaldron/clonez/engine262/dist/engine262.js with error: Identifier directly after number (2333:33)
```

Here's the line: 

```
this.scannedValue = 0n;
```

**Comment by devsnek** [comment]
You will need to use instrumentation that supports bigints.

**Comment by rwaldron** [comment]
Sure, that makes sense, but this is from running the tools in _this_ repo, as provided.

**Comment by rwaldron** [comment]
Do I need to dump `node_modules/*` and re-npm install?

**Comment by devsnek** [comment]
Most likely something is wrong with your install. I'm able to collect coverage locally, and of course the CI uses that script.

**Comment by rwaldron** [comment]
I've just nuked the installation and that issue appears to have vanished, but as with any dependency issue it will haunt me 🤣
