### ISSUE TITLE
Multiple iteration labels

### ISSUE THREAD

**Issue by lachrist** [engine262/engine262#150]
Hi,

This throws a syntax error in engine262:

```js
foo: bar: while (false) continue foo;
```

From what I could understand from the spec, multiple labels in front of an iteration statement should all be considered as iteration label and be valid as continue label.

https://www.ecma-international.org/ecma-262/11.0/index.html#sec-labelled-statements-static-semantics-containsundefinedcontinuetarget
https://www.ecma-international.org/ecma-262/11.0/index.html#sec-while-statement-static-semantics-containsundefinedcontinuetarget

Kind regards,
And thanks for the project!

**Comment by TimothyGu** [comment]
BTW the correct citation is https://tc39.es/ecma262/#sec-labelled-statements, which says:

> A _Statement_ may be prefixed by a label. … A _Statement_ can be part of a _LabelledStatement_, which itself can be part of a _LabelledStatement_, and so on. The labels introduced this way are collectively referred to as the “current label set” when describing the semantics of individual statements.
