### ISSUE TITLE
Feature inquiry: async evaluation

### ISSUE THREAD

**Issue by mkshio** [engine262/engine262#160]
👋🏼  Hi all, great work!  I'm super happy to see a spec-compliant metacircular interpreter for ES.

Similar to https://github.com/engine262/engine262/issues/149, I'm interested in utilizing engine262 as a code-stepper.  In my case it's in a browser context, so there's shaky support for Atomics.

I was wondering - would it be within scope to modify the engine to allow code evaluation to suspend until receiving a resume signal?  For example, `onNodeEvaluation` could return a promise, thereby pausing execution until the user chooses to proceed.

**Comment by devsnek** [comment]
This is technically possible but it would require rewriting every function call which could possibly call into the vm into an await/yield. Currently this is only done inside the evaluation code itself, and the boundaries have `unwind` calls which greedily consume the generator.

**Comment by mkshio** [comment]
Thanks for the quick reply!  I see what you mean re: async proliferation.  Let me know if you're considering migrating someday.

For my use case, I'll just have `onNodeEvaluation` push all evals of interest into a buffer and play it back.
