### ISSUE TITLE
Is it possible to save the current state and then fallback back to it later?

### ISSUE THREAD

**Issue by ChrisAcrobat** [engine262/engine262#191]
I haven't found anything on savning the current state and being able to revert it back to it as a safe point.
A workaround would be to save all successfully added source and then re-evaluate it all again when problem occurs, but what could quickly become resource heavy. So I would be happy if someone could share a working solution. 🙂

Thanks for the help!

**Comment by devsnek** [comment]
this is not possible. the closest you can get is probably something like this: https://github.com/engine262/engine262/blob/main/test/stepped.js
