### ISSUE TITLE
Use TypeScript?

### ISSUE THREAD

**Issue by Jack-Works** [engine262/engine262#202]
TypeScript can help find type mismatch problems in the code. Since engine262 is a step-to-step implementation of ECMA262 spec, type error in this project also indicates there might be a bug or ambiguity in the ECMA262.

**Comment by Jack-Works** [comment]
I'd like to create PR to gradually add TypeScript if maintainers think it is a good idea

**Comment by devsnek** [comment]
I suppose it would be okay.... I've really enjoyed the idea of this being pure js but I get how typescript would help.

**Comment by Jack-Works** [comment]
It's also possible to annotate the project with JSDoc and type check it with tsc, but it will be less readable (e.g. a 2 parameter function can be typed in one line in typescript but need 5 lines of comments for JSDoc)

**Comment by Jack-Works** [comment]
we're already on the road
