### ISSUE TITLE
Can't load module

### ISSUE THREAD

**Issue by ChrisAcrobat** [engine262/engine262#226]
I'm trying to execute any of the [cannon-es](https://github.com/pmndrs/cannon-es/tree/master/dist) files in [engine262.js.org](https://engine262.js.org/) by Copy/Paste, but I am unable.
I guess that modules are not supported, but please confirm.

**Comment by devsnek** [comment]
It seems to be working for me, can you be more specific about what isn't working?

**Comment by Jack-Works** [comment]
<img width="314" src="https://github.com/engine262/engine262/assets/5390719/899df273-e5bd-415a-afba-a46870263a38">

make sure you choose `module`, not `script`

**Comment by ChrisAcrobat** [comment]
> <img alt="" width="314" src="https://user-images.githubusercontent.com/5390719/258630009-899df273-e5bd-415a-afba-a46870263a38.png">
> make sure you choose `module`, not `script`

Thank you, my mistake. 🤦
