### ISSUE TITLE
Sample from README.md fails to run

### ISSUE THREAD

**Issue by passionate-bram** [engine262/engine262#231]
When running the sample shown in README.md:

```js
import { Agent, setSurroundingAgent, ManagedRealm, Value, CreateDataProperty, inspect } from "engine262";

const agent = new Agent({});
setSurroundingAgent(agent);

const realm = new ManagedRealm({});

realm.scope(() => {
  // Add print function from host
  const print = Value((args) => {
    console.log(...args.map((tmp) => inspect(tmp)));
    return Value.undefined;
  });
  CreateDataProperty(realm.GlobalObject, Value('print'), print);
});
```

# Error

When running I get an error from the `Value` constructor, it is triggering the `default` case of the switch block.
Looking at the code I imagine that the callback is supposed to be the actual value being stored.
Please update the sample in README.md, perhaps the Value's API has changed since it was written.

# My environment

Additionally, should it be of concern, my environment is not entirely standard:

In my case I have not installed engine262 through npm but as a git submodule.
The submodule is currently checked out at `1582a0c3b2b75eaa81d5c535852d632de7e7a28a`.
After a full build following the README's instructions, my code imports the engine by the `dist/engine262.mjs` artifact.

My code is being compiled by a boilerplate vite project (preset: vanilla, javascript).

**Comment by Jack-Works** [comment]
Oh sorry! Yes, Value API has changed 6 months ago.

```diff
-const onRejected = Value(rejectedClosure);
+const onRejected = CreateBuiltinFunction(rejectedClosure, 1, Value(''), []);
```

I'll update readme soon
