### ISSUE TITLE
Bundle typescript definitions for improved code completion to library users

### ISSUE THREAD

**Issue by passionate-bram** [engine262/engine262#232]
The codebase currently compiles the library to `engine262.js` and `engine262.mjs`.
The codebase is also written in typescript, with large parts of the public API having its type annotated (if not the return values then at least the inputs).

While using this library I noticed that my IDE (webstorm) is providing bare-bones autocompletion, basically only exported symbols are suggested. No type information is given.

There are various plugins for rollup to bundle and extract the typescript definitions of the library.

Currently you are using babel, mostly for the transformer I assume, but perhaps the official typescript plugin for rollup could be considdered to replace it (together with a ts transformer that does the X and Q rewrites used in the project).

**Comment by passionate-bram** [comment]
I'm willing to help out with this, as having the project produce a `engine262.d.ts` would massively help my effort as well.

My project will end up needing a modified version of e262 anyway, so having better integration with the types will do well early on also.

**Comment by passionate-bram** [comment]
I'm going to investigate https://github.com/wessberg/rollup-plugin-ts#combining-typescript-with-babel as a possible solution, as it supports babel as well.

**Comment by Jack-Works** [comment]
out-of-box typescript is available since 0.0.1-dd05c163162914b12baca4fbabb6e9ce99a217bc (just published)

**Comment by passionate-bram** [comment]
Thanks for adding the types, so quick too very much appreciated!
