### ISSUE TITLE
Syntax issues with strict mode and eval

### ISSUE THREAD

**Issue by targos** [engine262/engine262#69]
There are a number of issues related to strict mode and eval and I'm not sure how we should proceed to fix them.

I already monkey patched acorn to allow forcing the strict flag to true (used when eval is called in a strict context). 

Some problems that I saw with the current state of things:
- we cannot eval code that is only valid in a specific context
- there are new constructs, like classes, that are always strict, even in sloppy mode. The current way our runtime strict checking is implemented (strict flag in AST nodes) doesn't work with that.

**Comment by TimothyGu** [comment]
> there are new constructs, like classes, that are always strict, even in sloppy mode. The current way our runtime strict checking is implemented (strict flag in AST nodes) doesn't work with that.

That is an Acorn bug, which is fixed on Acorn master:
