### ISSUE TITLE
Spec changes

### ISSUE THREAD

**Issue by targos** [engine262/engine262#72]
- [x] https://github.com/tc39/ecma262/pull/1412
- [x] https://github.com/tc39/ecma262/pull/1416
- [x] https://github.com/tc39/ecma262/pull/1330
- [x] https://github.com/tc39/ecma262/pull/1433 (is our implementation already stable? yup)
- [ ] https://github.com/tc39/ecma262/pull/1372
- [x] https://github.com/tc39/ecma262/pull/1378 (parser only)
- [x] https://github.com/tc39/ecma262/pull/1480

stage 4 and incoming after weekly editor meeting:

- [x] https://github.com/tc39/ecma262/pull/1274 `Object.fromEntries`
- [x] https://github.com/tc39/ecma262/pull/1396 `JSON.stringify` revision
- [x] https://github.com/tc39/ecma262/pull/1309 `Array.p.{flat,flatMap}`
- [x] https://github.com/tc39/ecma262/pull/1275 `String.p.{trimStart,trimEnd,trimLeft,trimRight}`
- [x] https://github.com/tc39/ecma262/pull/1346
- [x] https://github.com/tc39/ecma262/pull/697
- [x] https://github.com/tc39/ecma262/commit/b012019fea18f29737a67c36911340a3e25bfc63

**Comment by TimothyGu** [comment]
Merged into #82.
