### ISSUE TITLE
ecma262 changes

### ISSUE THREAD

**Issue by devsnek** [engine262/engine262#82]
- [x] https://github.com/tc39/ecma262/commit/25745fe7e5e5c51bcef96dbbd762008e58cb41a7      
- [ ] https://github.com/tc39/ecma262/commit/94c6f97be34f49f14907dc39517774b7d8e49577
- [x] https://github.com/tc39/ecma262/commit/a25df663ddaa8f0b976f0411681635f587be63e0
- [x] https://github.com/tc39/ecma262/commit/448a356e7c6f290c59198b792af233fc4f184cfa
- [x] https://github.com/tc39/ecma262/commit/01d950f3cea38a7f83d2f8e4a4792de99ee9e02c
- [x] https://github.com/tc39/ecma262/commit/f158df16b4bfa4d8d1efa7407ebfe8eeb339f4fd
- [x] https://github.com/tc39/ecma262/commit/844c8e8febfb8b4a6c104adf03245be18c99b373
- [x] https://github.com/tc39/ecma262/commit/71927e139558de94252e67bb198e4904df7858c5
- [x] https://github.com/tc39/ecma262/commit/d6431719a8a911f7b9f719bdc8511abdc5b69a01
- [x] https://github.com/tc39/ecma262/commit/143931e9feab858402014cc80c7d163560e2ba99
- [x] https://github.com/tc39/ecma262/commit/c012f9c70847559a1d9dc0d35d35b27fec42911e
- [x] https://github.com/tc39/ecma262/commit/46eb1380fb47d84bc904a40904609042328c5eeb
- [x] https://github.com/tc39/ecma262/commit/a2647114b7f2d42b02e7c04c8c3a05787846f6e5
- [x] https://github.com/tc39/ecma262/commit/fe9b81af43fbfe6fef9967a577fcda0a094e4661
- [x] https://github.com/tc39/ecma262/commit/7428c89bef626548084cd4e697a19ece7168f24c
- [x] https://github.com/tc39/ecma262/commit/517f09a9d08e3c8a8963302c9d7c0d69b03e0004
- [x] https://github.com/tc39/ecma262/commit/3e2943d9cbf49b9352f60c17e494d8079c1bdfd0
- [x] https://github.com/tc39/ecma262/commit/8a16cb8d18660a1106faae693f0f39b9f1a30748
- [ ] https://github.com/tc39/ecma262/commit/a6d940eb00ee7809c365eb1158ade1947da43741
- [x] https://github.com/tc39/ecma262/commit/a561c8810a2d19507342bfd485dbedca23edbb9b
- [x] https://github.com/tc39/ecma262/commit/257cae9f69068704fc9e89a729f54bd7977c9161
- [x] https://github.com/tc39/ecma262/commit/9da8fb6ae36899341a3694a4c6af111981b60831
- [x] https://github.com/tc39/ecma262/commit/3e38b659850ec49ccf49f74ec1290795825b956a
- [x] https://github.com/tc39/ecma262/commit/578dd55b4dc727355ec28ffaeecd69196ba8a6d8
- [x] https://github.com/tc39/ecma262/commit/691173a72434ccf0ac7cc0104d1eecb6d0c740e7
- [x] https://github.com/tc39/ecma262/commit/44e80585bcf293d1e644d74f13b0462bec5df57f
- [x] https://github.com/tc39/ecma262/commit/ef0cf19e78b227c768751b13d877fa27bfb38266
- [x] https://github.com/tc39/ecma262/commit/62225e4dd20b3221c9e7b9bd02374064d31e6b34
- [x] https://github.com/tc39/ecma262/commit/fb23016a1e9df4db092b2861f8b048d6aa457cd0
- [x] https://github.com/tc39/ecma262/commit/2e2a3d430cba6fb108d03e4c6176ed17d4854c7b
- [x] https://github.com/tc39/ecma262/commit/02f414c785332a68da2e9563ae883db375e1714a
- [x] https://github.com/tc39/ecma262/commit/871f915188625adf0a2a6d940f48820d281ef5f6
- [x] https://github.com/tc39/ecma262/commit/cef8d4906c66c4e66f32ed894dfb0fc74efbf694

**Comment by TimothyGu** [comment]
Updated: we haven't implemented tc39/ecma262@a6d940e yet.

**Comment by TimothyGu** [comment]
Closing in favor of #85.
