### ISSUE TITLE
BigInt not listed in requirements

### ISSUE THREAD

**Issue by mischnic** [engine262/engine262#83]
BigInts are used in `src/grammar/Scientific.mjs` https://github.com/engine262/engine262/blob/2c51032de80ce7e770cedb0900e090fb84c4f62b/src/grammar/Scientific.mjs#L6-L16 but are not listed as a runtime requirement in https://github.com/engine262/engine262#requirements

**Comment by devsnek** [comment]
feel free to open a pr :)
