### ISSUE TITLE
import and run api.mjs directly

### ISSUE THREAD

**Issue by caub** [engine262/engine262#88]
Hi, great work in this project, congrats

I'd like to know if it's possible to run directly src/api.mjs (because I'd like to debug in depth, and plan to a new feature, slice-notation probably)

example: 

```js
import { Realm, initializeAgent } from "./src/api.mjs";

initializeAgent({
  // onDebugger() {},
  // ensureCanCompileStrings() {},
  // promiseRejectionTracker() {},
  // hasSourceTextAvailable() {},
  // onNodeEvaluation() {},
  // features: [],
})

const realm = new Realm({
  // resolveImportedModule() {},
});

realm.evaluateScript(`
1+1999
`);
```

I use `node --experimental-modules`, but when running this, I get this error: 
```
file:///home/caub/dev/engine262/src/completion.mjs:98
  throw new TypeError('ReturnIfAbrupt requires build');
        ^

TypeError: ReturnIfAbrupt requires build
```
If I'm running api.mjs programmatically like this, I wouldn't need completions, if that can help

**Comment by devsnek** [comment]
Q, X, and ReturnIfAbrupt are macros, and they have to be replaced. There's no way to run without building. Building is very fast (like 3-5 seconds), and everything has source map support, so it hasn't been much of a problem.

**Comment by caub** [comment]
Ok, yes it works I can debug
