### ISSUE TITLE
Bug: "match print to other engines, add console" commit breaks stdout

### ISSUE THREAD

**Issue by rwaldron** [engine262/engine262#92]
The commit "[match print to other engines, add console](https://github.com/engine262/engine262/commit/ab3cffce3d77715571e45770f3e40cd9ca2f45ce
)" intentionally adds a space to `stdout` ([here](https://github.com/engine262/engine262/commit/ab3cffce3d77715571e45770f3e40cd9ca2f45ce#diff-49f4289875bb3beb760f5c550f5aaf0eR53)) in the name of "matching" other engines—but no other engine adds an extra space at the end of the line like this. I discovered this while running eshost tests that subject all engines to the same tests, with the same expected outcomes. 

Here's the test that caught the bug (the value of `result.stdout` comes directly from the child shell process that ran the test code): 

```js
it('gathers stdout', () => {
  return agent.evalScript('print("foo")').then(result => {
    assert(result.stdout.match(/^foo\r?\n/), `Unexpected stdout: ${result.stdout}`);
  });
});
```

Current engine262 result:

```
{ stderr: '', stdout: 'foo \n', error: null }
                          ^
```

Which disagrees with every other engine...

ChakraCore:
```
{ stderr: '', stdout: 'foo\n', error: null }
```

Hermes: 
```
{ stderr: '', stdout: 'foo\n', error: null }
```

V8:
```
{ stderr: '', stdout: 'foo\n', error: null }
```

JSShell
```
{ stderr: '', stdout: 'foo\n', error: null }
```

JavaScriptCore
```
{ stderr: '', stdout: 'foo\n', error: null }
```

Furthermore, the implementation here doesn't agree with itself—these occurrences still output the correct, expected string: 

- https://github.com/engine262/engine262/commit/ab3cffce3d77715571e45770f3e40cd9ca2f45ce#diff-49f4289875bb3beb760f5c550f5aaf0eR67
- https://github.com/engine262/engine262/commit/ab3cffce3d77715571e45770f3e40cd9ca2f45ce#diff-49f4289875bb3beb760f5c550f5aaf0eR74
- https://github.com/engine262/engine262/commit/ab3cffce3d77715571e45770f3e40cd9ca2f45ce#diff-49f4289875bb3beb760f5c550f5aaf0eR81

**Comment by devsnek** [comment]
The behaviour i was trying to duplicate was that `print(a, b, c)` where trying to print `b` throws still results in `a` being printed. The space is indeed a bug, and console uses separate logic because it doesn't print incomplete results.

**Comment by rwaldron** [comment]
Thanks for the quick fix! ❤️
