### ISSUE TITLE
WeakMap is cleaned up too aggressively

### ISSUE THREAD

**Issue by mhofman** [engine262/engine262#97]
WeakMap entries are too aggressively collected. If a key is reachable through another WeakMap entry, it will be collected nonetheless, resulting in unexpected results.

```js
const map = new WeakMap();

let obj1 = {};

{
  let obj2 = {};
  map.set(obj1, obj2);
  map.set(obj2, 'Where did I go?');
}

// Trigger gc()
await Promise.resolve();

// And another?
await Promise.resolve();

// prints: true undefined
console.log(map.has(obj1), map.get(map.get(obj1)));
```

The leaky solution would be to associate WeakMap instances to the object keys (basically what most WeakMap polyfills do). The non-leaky approach would be to use ephemerons.

Interesting discussion on the subject: https://github.com/tc39/ecma262/issues/1657

**Comment by devsnek** [comment]
@mhofman ephemeron seems the most reasonable, i believe this fixes it?

```diff
diff --git a/src/api.mjs b/src/api.mjs
index 62b13e8..35d4962 100644
--- a/src/api.mjs
+++ b/src/api.mjs
@@ -104,6 +104,14 @@ function mark() {
 
   markCb(surroundingAgent);
 
+  weakmaps.forEach((map) => {
+    map.WeakMapData.forEach((r) => {
+      if (marked.has(r.Key)) {
+        markCb(r.Value);
+      }
+    });
+  });
+
   if (surroundingAgent.feature('WeakRefs')) {
     weakrefs.forEach((ref) => {
       if (!marked.has(ref.WeakRefTarget)) {
```

**Comment by devsnek** [comment]
This should be fixed now. Let me know if anything else isn't working as expected.
