### ISSUE TITLE
TC39 Realms proposal and engine262

### ISSUE THREAD

**Issue by pabloalmunia** [engine262/engine262#98]
Now the TC39 Reañms proposal is in stage 2 level.

https://github.com/tc39/proposal-realms

Engine 262 define a Realm class, but the interfaces is not the same. Maybe it's a good idea to adjust both.

**Comment by devsnek** [comment]
@pabloalmunia are you referring to `$262.createRealm`? That's an API used by test262 tests (https://github.com/tc39/test262/blob/master/INTERPRETING.md).

**Comment by pabloalmunia** [comment]
This is a very simple example with the new Realms proposal:

```js
let r = new Realm(); // root realm

let f = r.globalThis.eval("(function() { return 17 })");

f() === 17 // true
```

I want to use engine262 Realm API with this interface, some as:

```js
const {Realm} = require('engine262');

let r = new Realm(); // root realm

let f = r.globalThis.eval("(function() { return 17 })");

f() === 17 // true
```

Offcourse, I can create a custom transformer wrapper between original interface and the new proposal...

**Comment by devsnek** [comment]
That realm is not the realms proposal, it is a realm record: https://tc39.es/ecma262/#realm
